### ISSUE TITLE
Doesn't work with pass 1.6.3

### ISSUE THREAD

**Issue by sigio** [morphje/ansible_pass_lookup#1]
Pass 1.6.3 sends errors to stderr...

**Comment by morphje** [comment]
True. pass 1.6.3 sends the stderr '$passname is not in the password store' 
Older version 1.4.3 (ubuntu 14.04 LTS) appears to write to stdout :(

**Comment by morphje** [comment]
Fixed: patched check_output2 method. Included stderr to the output. 
(checked on sigio's laptop ;) )
